Feat/comment REST API 구현
chaewonni/FreshmanCommunity pull request #11
Opened 2024-02-09 10:38 UTC by jettieb

## 📚개요
Comment의 기본 Get,Post,Patch,Delete 구현하였습니다. 

## 💡Key Changes

- Comment entity, dto, controller, service 추가
- 좋아요 개수 측정을 위한 likeComment entity 추가

## ✅To Reviewers
좋아요를 likeComment DB와 연결해서 list형태로 통째로 받아서 db에 저장하는 방법도 있고, 아니면 likeComment DB와 연결 없이 단순 Integer로 해놓고 delete/insert 요청이 들어올때마다 +1/-1 하는 방식도 있는 것 같습니다.
후자를 택하긴 했는데 이외에도 아이디어 있으면 알려주세요!

## 🎓Reference
댓글 좋아요수 db에 저장 : https://hogwart-scholars.tistory.com/entry/Spring-Boot-count%EB%A5%BC-%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94-5%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95

2024-02-09 11:23 UTC, chae-jpg requested changes
CRUD 다 구현하시느라 정말 수고 많으셨습니다!💚 코멘트 몇 가지만 확인 부탁드립니다🙏

2024-02-09 11:23 UTC, chae-jpg commented on server/src/main/java/teamFive/freshmanCommunity/dto/CommentDto.java
> +    private Article article;    //article FK
여기서 멤버랑 아티클을 바로 받아오는 게 아니라  memberId, articleId를 받아오는 걸로 저는 알고 있었는데, id 거쳐서 데이터를 받아오는 게 아니라 엔티티에서 바로 데이터를 가져오려고 이렇게 구현하신 건가요?

2024-02-09 11:23 UTC, chae-jpg commented on server/src/main/java/teamFive/freshmanCommunity/service/CommentService.java
> +                .orElseThrow(()-> new IllegalArgumentException("해당 게시물이 존재하지 않습니다."));
예외 처리 좋아요👍👍
저랑 채원님이 해주신 것 보고 예외 처리 방식 통일해주시면 좋을 것 같습니다!

2024-02-09 11:23 UTC, chae-jpg commented on server/src/main/java/teamFive/freshmanCommunity/entity/Comment.java
> +    //리스트형태로 저장? 아니면 그냥 숫자만 저장할지..
오옹 이 방법도 좋은데, 혹시 이대로 구현하면 게시글에 유저가 좋아요를 눌렀었는지 안 눌렀었는지는 어떻게 알 수 있나요??

2024-02-09 16:02 UTC, jettieb commented on server/src/main/java/teamFive/freshmanCommunity/service/CommentService.java
> +                .orElseThrow(()-> new IllegalArgumentException("해당 게시물이 존재하지 않습니다."));
네넵 빠른시일내에 예외처리 통일해서 올리도록 하겠습니다!!

2024-02-09 16:04 UTC, jettieb commented on server/src/main/java/teamFive/freshmanCommunity/entity/Comment.java
> +    //리스트형태로 저장? 아니면 그냥 숫자만 저장할지..
좋아요 눌렀는지는 좋아요db안에서 따로 확인할 수 있을 것 같아요!
좋아요DB에 memberId랑 commentId 저장하니까 이걸로 해당 유저가 좋아요 눌렀는지 상태를 확인할 수 있지 않을까요?!

2024-02-09 16:32 UTC, jettieb commented on server/src/main/java/teamFive/freshmanCommunity/dto/CommentDto.java
> +    private Article article;    //article FK
저희 책 14장이나, https://cjw-awdsd.tistory.com/47
이 티스토리 보시면 전부 바로 member나 article을 받아오더라고요!
잘 모르겠긴 한데 댓글에서 바로 게시글을 찾아갈 수 있도록 참조형이 Member이나 Article인 것 같아요

2024-02-10 07:06 UTC, chae-jpg commented on server/src/main/java/teamFive/freshmanCommunity/dto/CommentDto.java
> +    private Article article;    //article FK
아항 그렇군요! 그게 더 편리해 보이네요 저도 그렇게 해야겠어요ㅎㅎ

2024-02-10 07:06 UTC, chae-jpg commented on server/src/main/java/teamFive/freshmanCommunity/entity/Comment.java
> +    //리스트형태로 저장? 아니면 그냥 숫자만 저장할지..
아아 그러면 되겠네요! 알겠습니다👍

2024-02-11 11:38 UTC, jettieb commented on server/src/main/java/teamFive/freshmanCommunity/dto/CommentDto.java
> +    private Article article;    //article FK
헐죄송해요!!!ㅠㅠ 제가 엔티티 말씀하시는줄알고ㅠ 
dto라면 말씀해주신대로 memberId, articleId를 int형태로 받아오는게 더 맞겠네요!!ㅠ 감사해요 수정하겠습니다!

2024-02-11 17:08 UTC, chaewonni approved these changes

2024-02-11 17:08 UTC, chaewonni commented on server/src/main/java/teamFive/freshmanCommunity/api/CommentApiController.java
> +    public ResponseEntity<CommentDto> create(@PathVariable Long articleId, @RequestBody CommentDto dto){
예를 들어 댓글을 생성할 때는 commentDto에서 다 받아오는 게 아니라 content만 받고, member나 major등은 로그인된 유저의 세션에서 가져와야 하지 않을까요??!

2024-02-11 18:04 UTC, jettieb commented on server/src/main/java/teamFive/freshmanCommunity/api/CommentApiController.java
> +    public ResponseEntity<CommentDto> create(@PathVariable Long articleId, @RequestBody CommentDto dto){
네 안그래도 고민하다가 지금 수정중이었습니다!
기존 코드는 commentDto중에서 api로 안들어온 값은 어차피 null로 저장되길래 제가 그중에서 comment 부분만 컨트롤하려고 했는데..
채원님 로그인 dto 보니까 그게 더 나을것 같아서 수정중이었습니다~! 감사합니다!

2024-02-12 00:05 UTC, chae-jpg approved these changes

2024-02-12 00:05 UTC, chae-jpg commented on server/src/main/java/teamFive/freshmanCommunity/service/CommentService.java
> +                .orElseThrow(()-> new BoardNotFoundException());
BoardNotFoundException이 majorId가 존재하지 않을 때 예외라서 게시글이 없는 경우는 다른 예외를 새로 만드는 게 구분할 때 더 편할 것 같습니다!

2024-02-13 08:59 UTC, jettieb commented on server/src/main/java/teamFive/freshmanCommunity/service/CommentService.java
> +                .orElseThrow(()-> new BoardNotFoundException());
어 아 message글이 "존재하지 않는 게시판입니다" 길래 그냥 없는 게시판일때 사용하는 예외인줄 알았네요!..
네 예외 새로 만들어서 수정하겠습니다~!
아 그러면 혹시 메세지 내용 majorId가 존재하지 않을때의 존재하지 않는 게시판이라고 수정해주실 수 있나요?! 나중에 헷갈릴 수도 있을 것 같아서요!

2024-02-13 11:10 UTC, merged

2024-02-13 15:03 UTC, chae-jpg commented on server/src/main/java/teamFive/freshmanCommunity/service/CommentService.java
> +                .orElseThrow(()-> new BoardNotFoundException());
넵 그렇게 수정하겠습니다! 감사합니다!